### ISSUE TITLE
Revanced twitter

### ISSUE THREAD

**Issue by Artiyke** [beans-321/revanced-auto-apk#1]
The revanced Twitter ain't working. The material ui still there

**Comment by bean-factory** [comment]
Works for me. Could you please share some screenshots?

**Comment by Artiyke** [comment]
I already uninstalled it. I tried patching too 
![Screenshot_20230107-200102](https://user-images.githubusercontent.com/121959262/211512604-dffff45b-baa2-44ae-8b4c-5e17e40157c4.png)

**Comment by bean-factory** [comment]
I'm not sure I understand. The APKs in the releases are already patched. You can view build.conf to see the applied patches. If you want to use different patches you can make a fork of the repo.

**Comment by Artiyke** [comment]
Can you please drop the link of the apk file
