### ISSUE TITLE
Ask for adding switch of premium icon of youtube

### ISSUE THREAD

**Issue by kil011** [beans-321/revanced-auto-apk#2]
Hi, thanks for you hard work for these apps.When I'm using youtube, it's perfect. 

But I would like to ask if you can add a switch for premium icon for this app (left upper area) so that we could convert premium icon to original one (YouTube instead of premium).

Best

**Comment by bean-factory** [comment]
You can clone the repo and remove 'force-premium-heading' from YOUTUBE_INCLUDED_PATCHES in build.conf.

**Comment by kil011** [comment]
Will it work if my device is not rooted?

**Comment by bean-factory** [comment]
Yes, you will need to install Vanced MicroG from https://github.com/inotia00/VancedMicroG

**Comment by kil011** [comment]
Sure. If you could send me how to remove patch from build.conf, I would be very grateful
