### ISSUE TITLE
build.conf  "auto" not working as intended

### ISSUE THREAD

**Issue by STEK1337** [beans-321/revanced-auto-apk#3]
Hello, Im new to GitHub, don't know if this is the right way to tell you about the issue

I forked your repo, made some changes to my likings but the code for auto detection for the latest revanced-extended-patches supported version is not working as it should, it downloads older version of youtube. If i put "latest" it downloads even older version of youtube, also for tiktok "auto" or "latest" downloads the beta version instead of following the latest revanced-extended-patches supported version. If I want to download the recommended version of the apk I need to use "custom" option. Can you look into it please

**Comment by bean-factory** [comment]
Fixed.
