### ISSUE TITLE
patches "excluded by default"

### ISSUE THREAD

**Issue by STEK1337** [beans-321/revanced-auto-apk#4]
Don't know if this is problem in revanced patches but some patches are excluded by default. I need to manually enter them so the patch can succeed.
INFO: Skipping materialyou: Excluded by default
INFO: Skipping force-premium-heading: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default

**Comment by bean-factory** [comment]
The decision to exclude these patches by default has been made by the ReVanced devs. You can add them to the included patches in build.conf if you want to enable them.
