### ISSUE TITLE
remove useless options.toml

### ISSUE THREAD

**Issue by STEK1337** [beans-321/revanced-auto-apk#5]
needs update or file is useless, there is no patch options such as: YouTube_AppName, YouTube_PackageName, Music_PackageName, Custom_Speed_Arrays & Overlay_Buttons_Icon

https://github.com/beans-321/revanced-auto-apk/actions/runs/4417817838/jobs/7744063088#step:6:973

**Comment by bean-factory** [comment]
Fixed. Thank you for all the issues :)
