### ISSUE TITLE
speed up workflows

### ISSUE THREAD

**Issue by STEK1337** [beans-321/revanced-auto-apk#7]
Is it possible to use caching to speed up workflows?

**Comment by bean-factory** [comment]
I'm a bit busy currently with school and stuff but I'll try to work on this sometime in the future. Although I doubt how useful this will be as the time taken to actually build isn't that long compared to the intervals the check for new releases happens.

**Comment by STEK1337** [comment]
As I said, Im new to github, don't have experience with coding/adding new stuff, saw some posts about speeding up workflows with cache on google and was curious if we can implement it in the builder. Thanks for replying.
