### ISSUE TITLE
Add a list of patches used for each apk, in a summary/detail section

### ISSUE THREAD

**Issue by fenglengshun** [beans-321/revanced-auto-apk#8]
Hi, I'm interested in using this builder's apk, but I'm not entirely clear on what patches are used for each of them.

I'd like to suggest that in the readme, release note (if it's compatible), and the website to use the details/summary tag so that the patches can be listed without taking too much space, like so:

<details><summary>Patch List</summary><p>

- YouTube: {patches}
- YouTube-Music (arm64-v8a): {patches}
- YouTube-Music (arm-v7a): {patches}
- Instagram: {patches}
- Reddit: {patches}
- Twitch: {patches}
- Twitter: {patches}

</p></details>

**Comment by bean-factory** [comment]
Added to README
