### ISSUE TITLE
Fix options.toml

### ISSUE THREAD

**Issue by STEK1337** [beans-321/revanced-auto-apk#9]
Hello, script has mistakes about options.toml, lets fix them

1. Rename options.json --> options.toml
2. In utils.sh change $patcher_args --options=./options.toml" --> $patcher_args --options=options.toml
3. Done

**Comment by STEK1337** [comment]
https://github.com/STEK1337/revanced-extended/commit/20d32f09ecbe70760a3720a3affc3a7d33acdf17

https://github.com/STEK1337/revanced-extended/commit/70767038215524f17b1caff411900379d5ae8f61

**Comment by bean-factory** [comment]
Fixed https://github.com/beans-321/revanced-auto-apk/commit/a4f4b671caea41126190e14ce5ad797e262d88b3
